site:
  title: Documentation Hub
  start_page: hub::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_paths: [ ./docs ]
    - url: https://github.com/obfischer/maven-best-practices.git
      branches: [future]
    - url: https://github.com/obfischer/architecture-best-practices.git
      branches: [future]
    - url: https://github.com/obfischer/api-best-practices.git
      branches: [future]

ui:
  bundle:
    url: https://github.com/obfischer/antora-ui-obfischer/releases/download/2025-04-12/ui-bundle.zip
    snapshot: true

asciidoc:
  extensions:
    - asciidoctor-kroki
